[http.routers]
  [http.routers.cookiecloud]
    entrypoints=["https"]
    rule="Host(`cookiecloud.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "cookiecloud-service"

[http.services]
  [http.services.cookiecloud-service.loadBalancer]
    [[http.services.cookiecloud-service.loadBalancer.servers]]
      url = "http://10.99.1.2:8088/"